/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package latihanjavafx;

/**
 *
 * @author Fifi Agustina
 */
public class FrameIdealTubuh extends javax.swing.JFrame {

    /**
     * Creates new form FrameIdealTubuh
     */
    public FrameIdealTubuh() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jeniskelamin = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        idnama = new javax.swing.JTextField();
        idtinggi = new javax.swing.JTextField();
        idberat = new javax.swing.JTextField();
        rdblaki = new javax.swing.JRadioButton();
        rdbperempuan = new javax.swing.JRadioButton();
        buttonhitung = new javax.swing.JButton();
        buttonulang = new javax.swing.JButton();
        buttonkeluar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        idideal = new javax.swing.JTextField();
        idhasil = new javax.swing.JTextField();
        idsaran = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(102, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setText("Aplikasi cek ideal");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(240, 20, 140, 20);

        jLabel2.setText("Nama");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(78, 67, 80, 30);

        jLabel3.setText("Tinggi");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(77, 108, 90, 30);

        jLabel4.setText("Berat");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(77, 145, 90, 20);

        jLabel5.setText("Jenis Kelamin");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(78, 173, 120, 30);

        idnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idnamaActionPerformed(evt);
            }
        });
        jPanel1.add(idnama);
        idnama.setBounds(227, 59, 262, 31);
        jPanel1.add(idtinggi);
        idtinggi.setBounds(227, 101, 227, 28);

        idberat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idberatActionPerformed(evt);
            }
        });
        jPanel1.add(idberat);
        idberat.setBounds(227, 137, 227, 30);

        jeniskelamin.add(rdblaki);
        rdblaki.setText("Laki-laki");
        rdblaki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdblakiActionPerformed(evt);
            }
        });
        jPanel1.add(rdblaki);
        rdblaki.setBounds(227, 179, 76, 23);

        jeniskelamin.add(rdbperempuan);
        rdbperempuan.setText("Perempuan");
        rdbperempuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbperempuanActionPerformed(evt);
            }
        });
        jPanel1.add(rdbperempuan);
        rdbperempuan.setBounds(332, 179, 110, 20);

        buttonhitung.setText("Hitung");
        buttonhitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonhitungActionPerformed(evt);
            }
        });
        jPanel1.add(buttonhitung);
        buttonhitung.setBounds(232, 220, 80, 30);

        buttonulang.setText("Coba Ulang");
        buttonulang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonulangActionPerformed(evt);
            }
        });
        jPanel1.add(buttonulang);
        buttonulang.setBounds(324, 220, 100, 30);

        buttonkeluar.setText("Keluar");
        buttonkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonkeluarActionPerformed(evt);
            }
        });
        jPanel1.add(buttonkeluar);
        buttonkeluar.setBounds(437, 220, 80, 30);

        jLabel6.setText("cm");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(472, 108, 50, 30);

        jLabel7.setText("kg");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(472, 145, 50, 40);

        jLabel8.setText("Berat Badan Ideal Anda adalah");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(78, 280, 220, 20);

        jLabel9.setText("Hasil Analisa Kesehatan");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(78, 322, 260, 20);

        idideal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ididealActionPerformed(evt);
            }
        });
        jPanel1.add(idideal);
        idideal.setBounds(282, 280, 60, 30);

        idhasil.setText("?");
        jPanel1.add(idhasil);
        idhasil.setBounds(78, 347, 450, 32);

        idsaran.setText("?");
        jPanel1.add(idsaran);
        idsaran.setBounds(78, 385, 450, 31);

        jLabel10.setText("kg");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(350, 280, 50, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 620, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdbperempuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbperempuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbperempuanActionPerformed

    private void rdblakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdblakiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdblakiActionPerformed

    private void idnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idnamaActionPerformed

    private void ididealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ididealActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ididealActionPerformed

    private void idberatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idberatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idberatActionPerformed

    private void buttonkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonkeluarActionPerformed
        // TODO add your handling code here:
        dispose();
        System.exit(0);
    }//GEN-LAST:event_buttonkeluarActionPerformed

    private void buttonulangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonulangActionPerformed
        // TODO add your handling code here:
        idnama.setText("");
        idberat.setText("");
        idtinggi.setText("");
        idideal.setText("");
        idhasil.setText("");
        idsaran.setText("");
        jeniskelamin.clearSelection();
        
    }//GEN-LAST:event_buttonulangActionPerformed

    private void buttonhitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonhitungActionPerformed
        // TODO add your handling code here:
        double h = 0;
        double t = Double.valueOf(idtinggi.getText());
        double b = Double.valueOf(idberat.getText());
        String nama = idnama.getText();
        
        if(rdblaki.isSelected()){
            h = (t-100);
    }//GEN-LAST:event_buttonhitungActionPerformed
        else if (rdbperempuan.isSelected()){
            h = (t-104);
        }
        
        String temp = Double.toString(h);
        
        if(h<b){
            idideal.setText(temp);
            idhasil.setText("Maaf "+nama+"sepertinya anda Overweight");
            idsaran.setText("Sebaiknya "+nama+"melakukan olahraga secara teratur dan pola makan yang sehat");
        }
        
        else if(h>b){
            idideal.setText(temp);
            idhasil.setText("Maaf "+nama+" sepertinya anda Underweight");
            idsaran.setText("Sebaiknya "+nama+" melakukan olahraga teratur dan pola makan sehat");
        }
        
        else{
            idideal.setText(temp);
            idhasil.setText("Tubuh anda ideal");
            idsaran.setText("Tetap olahraga secara teratur dan jaga pola makan");
        }  
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameIdealTubuh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameIdealTubuh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameIdealTubuh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameIdealTubuh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameIdealTubuh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonhitung;
    private javax.swing.JButton buttonkeluar;
    private javax.swing.JButton buttonulang;
    private javax.swing.JTextField idberat;
    private javax.swing.JTextField idhasil;
    private javax.swing.JTextField idideal;
    private javax.swing.JTextField idnama;
    private javax.swing.JTextField idsaran;
    private javax.swing.JTextField idtinggi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.ButtonGroup jeniskelamin;
    private javax.swing.JRadioButton rdblaki;
    private javax.swing.JRadioButton rdbperempuan;
    // End of variables declaration//GEN-END:variables
}
